### ISSUE TITLE
Error when no selectors are founded

### ISSUE THREAD

**Issue by dinova-dtardia** [iconsauce/postcss-iconsauce#1]
Running with no selector in code give back error 
`Cannot create property 'postcssNode' on string 'Error: Icons map cannot be empty'`

Using this `iconsauce.config.js`
```javascript
module.exports = {
    content: [
        './src/**/*.{js,tsx}',
        './parts/**/*.html',
        './templates/**/*.html'
    ],
    plugin: [
      require('@iconsauce/material-icons'),
      require('@iconsauce/mdi-svg'),
      require('@iconsauce/mgg-icons')
  }
```
and executing cli `postcss src/iconsauce.css -o src/iconsauce_dist.css` on files without icon use I have the error.

**Environment:**
 - OS: Linux Ubuntu 20.04
 - Node: 17.9.0
 - Npm: 8.8.0

**Comment by vitto** [comment]
This shouldn't happen, we will try to reproduce the problem. Thanks for reporting.

**Comment by nicolatamburini** [comment]
I have released a patch for the issue, [here is a template](https://stackblitz.com/edit/node-4mquvp) were you can test it.
Let me know if it fixes your problem.

**Comment by dinova-dtardia** [comment]
I confirm that the patch solve the issue. Thank you!
